language: python

python:
  - 3.5
  - 3.6

# Executed for 3.5 AND 3.5 as the first "test" stage:
script:
  - python setup.py test

# This defines further stages that execute after the tests
jobs:
  include:
    - stage: deploy latest.datasette.io
      script:
        - pip install .
        - npm install -g now
        - python tests/fixtures.py fixtures.db fixtures.json
        - datasette publish now fixtures.db -m fixtures.json --name datasette-latest --token=$NOW_TOKEN
      on: travis-deploy-now
